npm publish packages/omelox 
npm publish packages/omelox-admin
npm publish packages/omelox-loader
npm publish packages/omelox-logger 
npm publish packages/omelox-monitor
npm publish packages/omelox-protobuf
npm publish packages/omelox-protocol 
npm publish packages/omelox-rpc
npm publish packages/omelox-scheduler
npm publish plugins/omelox-globalchannel-plugin
npm publish plugins/omelox-globalstatus-plugin
npm publish plugins/omelox-http-plugin
npm publish plugins/omelox-robot-plugin
npm publish tools/omelox-cli
npm publish tools/omelox-excel
npm publish tools/omelox-gen-route
npm publish tools/omelox-json-schema
npm publish tools/omelox-protoc
npm publish tools/omelox-robot