export const wsMapRoutes = { 'chess.clientHandler.c_enterScene': 'c_enterScene',
  'chess.clientHandler.c_getGameList': 'c_getGameList',
  'chess.clientHandler.c_getSceneConfig': 'c_getSceneConfig',
  'chess.clientHandler.c_leaveScene': 'c_leaveScene',
  'game.chessRankHandler.c_playerReady': 'c_playerReady',
  'game.chessRankHandler.c_playerUnReady': 'c_playerUnReady',
  'game.chessRankHandler.s_playerReady': 's_playerReady',
  'game.chessRankHandler.s_playerUnReady': 's_playerUnReady',
  'game.pokqznnHandler.c_addBet': 'c_addBet',
  'game.pokqznnHandler.c_robBanker': 'c_robBanker',
  'game.pokqznnHandler.c_selectCard': 'c_selectCard',
  'game.pokqznnHandler.s_betMulti': 's_betMulti',
  'game.pokqznnHandler.s_countdown': 's_countdown',
  'game.pokqznnHandler.s_initHandCards': 's_initHandCards',
  'game.pokqznnHandler.s_playerAddBet': 's_playerAddBet',
  'game.pokqznnHandler.s_playerRobBanker': 's_playerRobBanker',
  'game.pokqznnHandler.s_playerSelectedCard': 's_playerSelectedCard',
  'game.pokqznnHandler.s_robBankerMulti': 's_robBankerMulti',
  'game.pokqznnHandler.s_roomInfo': 's_roomInfo',
  'game.pokqznnHandler.s_setBanker': 's_setBanker',
  'game.pokqznnHandler.s_settlement': 's_settlement',
  'game.pokqznnHandler.s_showCard': 's_showCard',
  'connector.clientHandler.c_login': 'c_login',
  'game.lastwarHandler.c_attack': 'c_attack',
  'rank.playerHandler.onlyNotify': 'onlyNotify' }